In [6]:
import torch
torch.__version__
torch.cuda.is_available()

False

In [19]:
import torch
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
z = x + y
print(z)
print(z.size())

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


In [84]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([[1,2,3],[4,5,6]],
                 device=device)
y = torch.tensor([[7,8,9],[10,11,12]],
                 device=device)
z = x + y
print(z)
print(z.size())
print(z.device)

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])
cpu


In [24]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = x.to(device)
y = y.to(device)
z = x + y
z = z.to("cpu")

In [28]:
torch.randn(100,200)

tensor([[-0.0202,  1.1398, -0.4037,  ..., -1.2413,  1.7040,  0.2253],
        [-1.0555, -1.1624, -0.3124,  ...,  0.6938,  1.2034,  1.4404],
        [ 0.0476, -0.1784, -1.2514,  ...,  1.3199, -0.9069,  0.6805],
        ...,
        [ 0.0225, -0.2211,  0.6425,  ..., -0.4774, -1.1970, -1.0346],
        [-0.1131, -0.7409, -0.4923,  ..., -0.0262,  0.2809,  0.0612],
        [ 0.4439, -1.2744,  0.4951,  ..., -0.4245, -0.9967, -0.9065]])

In [30]:
torch.randint(5,10,(100,200))

100

In [37]:
torch.zeros(100,200)

torch.Size([100, 200])

In [42]:
torch.linspace(1, 500, steps=5)

tensor([  1.0000, 125.7500, 250.5000, 375.2500, 500.0000])

In [46]:
torch.logspace(1, 10, steps=10,base = 2)#2^1 -> 2^10

tensor([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512., 1024.])

In [49]:
x.ndim

2

In [50]:
x.grad

In [51]:
x.layout

torch.strided

In [88]:
w = torch.tensor([1,2,3], dtype=torch.float32)
# Use the casting method to cast to a new data type
w.int()       # w remains a float32 after the cast
w = w.int()   # w changes to an int32 after the cast
# Use the to() method to cast to a new type
w = w.to(torch.float64) 
w = w.to(dtype=torch.float64) # Python automatically converts data types during
# operations
x = torch.tensor([1,2,3], dtype=torch.int32)
y = torch.tensor([1,2,3], dtype=torch.float32)
z = x + y
print(z.dtype)

torch.float32


In [65]:
torch.empty(10,10)

tensor([[ 1.4215e+19,  4.4725e+21,  0.0000e+00,  0.0000e+00,  8.2905e+02,
          7.7128e+31,  2.9387e+29,  1.7965e+19,  2.0131e+02,  1.4215e+19],
        [ 4.4725e+21,  8.6218e+09,  8.9495e+08,  8.2905e+02,  7.7128e+31,
          1.7751e+28,  1.7965e+19,  2.0131e+02,  1.4215e+19,  1.8759e+28],
        [ 1.0325e-38,  1.5357e+13,  3.2764e+09,  1.7689e+31,  4.3985e+21,
          0.0000e+00,  8.9494e+08,  8.2905e+02,  7.7128e+31,  4.2964e+24],
        [-1.5729e+04, -4.4379e-42,  8.5661e-33,  4.5909e-41,  1.0991e+21,
          6.8002e+22,  9.8095e+11,  7.2231e+28,  0.0000e+00,  0.0000e+00],
        [ 2.1019e-44,  0.0000e+00,  8.6822e-33,  4.5909e-41,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  2.3796e+2

In [89]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(x)
print(x[1,1])
print(x[1,1].item())

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor(4)
4


In [90]:
print(x[:2,1])#just like dataframe

tensor([2, 4])


In [91]:
print(x[x<7])

tensor([1, 2, 3, 4, 5, 6])


In [92]:
print(x.t())#转置1

print(x.T)#转置2

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])


In [93]:
print(x.view((8,-1)))#to see how this x has been transformed

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])


In [94]:
y = torch.stack((x, x))# Combining tensors
print(y)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])


In [95]:
a,b = x.unbind(dim=1)# Splitting tensors
print(a,b)

tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])


In [128]:
x1 = torch.tensor([[8,7,6],[2,3,4],[5,6,7]],dtype = torch.float32)
x2 = torch.tensor([[111,2,3],[23,2,11],[88,7,34]],dtype = torch.float32)

In [101]:
x1

tensor([[8, 7, 6],
        [2, 3, 4],
        [5, 6, 7]])

In [105]:
torch.argmax(x1)#最大数字的位置

tensor(0)

In [123]:
torch.argmin(x1)#最小数字位置

tensor(3)

In [122]:
torch.mean(x1,1)#需要预先转换为float

tensor([7., 3., 6.])

- 比较关系
- 返回值为bool类型=>```True``` or ```False```

In [129]:
torch.eq(x1,x2)#compare X1 and X2   => x1 == x2

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [130]:
torch.ge(x1,x2)#if x1>x2 ????     => x1 > x2

tensor([[False,  True,  True],
        [False,  True, False],
        [False, False, False]])

In [131]:
torch.gt(x1,x2)# greater or equal to ">="      => x1 >= x2

tensor([[False,  True,  True],
        [False,  True, False],
        [False, False, False]])

In [132]:
torch.le(x1,x2)#less than "<"      => x1 < x2

tensor([[ True, False, False],
        [ True, False,  True],
        [ True,  True,  True]])

In [134]:
torch.lt(x1,x2)#less than or equal to "<="     => x1 <= x2

tensor([[ True, False, False],
        [ True, False,  True],
        [ True,  True,  True]])

In [135]:
torch.ne(x1,x2)#not equal to "!="     => x1 != x2

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [137]:
torch.isnan(x1)#is nall

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [139]:
torch.isfinite(x1)#is finite有限的

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

- useless things

In [140]:
torch.sort(x1)

torch.return_types.sort(
values=tensor([[6., 7., 8.],
        [2., 3., 4.],
        [5., 6., 7.]]),
indices=tensor([[2, 1, 0],
        [0, 1, 2],
        [0, 1, 2]]))

In [146]:
torch.topk(x1,1)

torch.return_types.topk(
values=tensor([[8.],
        [4.],
        [7.]]),
indices=tensor([[0],
        [2],
        [2]]))

In [156]:
print(torch.kthvalue(x1,1))
print(torch.kthvalue(x1,2))
print(torch.kthvalue(x1,4))
print(torch.kthvalue(x1,5))

torch.return_types.kthvalue(
values=tensor([6., 2., 5.]),
indices=tensor([2, 0, 0]))
torch.return_types.kthvalue(
values=tensor([7., 3., 6.]),
indices=tensor([1, 1, 1]))
torch.return_types.kthvalue(
values=tensor([2., 5., 0.]),
indices=tensor([4968310768429349900,                   0, 8101238313836347651]))
torch.return_types.kthvalue(
values=tensor([3., 6., 0.]),
indices=tensor([                  0,                   0, 3930721035628260568]))


In [160]:
x = torch.tensor([[1,2,3],[4,5,6]],
         dtype=torch.float, requires_grad=True)
print(x)

f = x.pow(2).sum()
print(f)


f.backward()
print(x.grad) # df/dx = 2x

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
tensor(91., grad_fn=<SumBackward0>)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
